//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Monthly_bill = new HashSet<Monthly_bill>();
            this.Tenant_of_flat = new HashSet<Tenant_of_flat>();
        }
    
        public int id_flat { get; set; }
        public decimal area_apartments { get; set; }
        public int count_tenant_of_flat { get; set; }
        public int flat_number { get; set; }
        public int id_building { get; set; }
        public int tenant_payment_account { get; set; }
        public Nullable<bool> is_zip { get; set; }
    
        public virtual Apartment_number Apartment_number { get; set; }
        public virtual Building Building { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monthly_bill> Monthly_bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_of_flat> Tenant_of_flat { get; set; }
    }
}
