//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    
    public partial class Flat_owner
    {
        public int payment_account { get; set; }
        public string person_name { get; set; }
        public string Surname { get; set; }
        public string person_second_name { get; set; }
        public decimal debt { get; set; }
        public Nullable<int> person_benefits { get; set; }
        public int id_flat { get; set; }
        public decimal area_apartments { get; set; }
        public int count_tenant_of_flat { get; set; }
        public int flat_number { get; set; }
        public int id_building { get; set; }
        public int tenant_payment_account { get; set; }
    }
}
