//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_services
    {
        public int id_list_of_services { get; set; }
        public decimal service_count { get; set; }
        public int service_id { get; set; }
        public int counter_id { get; set; }
        public int id_monthly_bill { get; set; }
        public decimal price { get; set; }
        public Nullable<bool> is_zip { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Monthly_bill Monthly_bill { get; set; }
        public virtual Service Service { get; set; }
    }
}
