//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Flat = new HashSet<Flat>();
            this.Tenant_of_flat = new HashSet<Tenant_of_flat>();
        }
    
        public int payment_account { get; set; }
        public string person_name { get; set; }
        public string Surname { get; set; }
        public string person_second_name { get; set; }
        public decimal debt { get; set; }
        public Nullable<int> person_benefits { get; set; }
        public Nullable<bool> is_zip { get; set; }
    
        public virtual Benefits Benefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_of_flat> Tenant_of_flat { get; set; }
    }
}
