//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.List_of_services = new HashSet<List_of_services>();
        }
    
        public int id_service { get; set; }
        public string name_of_the_service { get; set; }
        public string full_description { get; set; }
        public System.DateTime Date_of_contract_conclusion { get; set; }
        public int rate_id { get; set; }
        public int unit_id { get; set; }
        public Nullable<bool> is_zip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_of_services> List_of_services { get; set; }
        public virtual Rate Rate { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
