//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant_of_flat
    {
        public int id_flat { get; set; }
        public int tenant_payment_account { get; set; }
        public Nullable<bool> is_zip { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Person Person { get; set; }
    }
}
