//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_associat.DataBase.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public string apartment_number { get; set; }
        public string person_name { get; set; }
        public string Surname { get; set; }
        public string person_second_name { get; set; }
        public decimal debt { get; set; }
        public string benefits_name { get; set; }
        public decimal benefits_factor { get; set; }
    }
}
